name: Generate Podcast Feeds

on:
  push:
    branches:
      - main  # Ensure the workflow runs only on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Feed Generator
        uses: tundemy/podcast-generator@v1.0.0  # Specify a version or commit hash instead of 'main'
